### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by faizan002** [appleboy/jenkins-action#10]
Hi,
My jenkins is hosted on-prem with some self signed certificate. 
What is the easiest way to get around this ? 
I understand, the process runs inside a docker container and perhaps somehow I should be able to install certificate in that container ? 

+ I am running action on a self-hosted runner and if there is anything needs to be done there, I have control over it.

Thanks in advance for your hints.

**Comment by appleboy** [comment]
```
      - name: trigger multiple Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://example.com"
          user: "example"
          token: ${{ secrets.TOKEN }}
          job: "job_1,job_2"
          insecure: "true"
```

Please add `insecure: "true"`
