### ISSUE TITLE
Error missing Jenkins config 

### ISSUE THREAD

**Issue by Suryadhulipudi** [appleboy/jenkins-action#3]
Hi, Can somebody point me, what  i am missing here. Thanks in advance. 
<img width="1102" alt="Screenshot 2020-08-18 at 12 34 39 AM" src="https://user-images.githubusercontent.com/13795705/90434680-77332b80-e0eb-11ea-9900-1bb3b9d6f73c.png">

**Here is my yaml file**

```
name: trigger jenkins job
on: 
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://10.0.0.1:8080"
        user: "jenkins"
        token: ${{ secrets.jenkins }}
        job: "abc"
```
