### ISSUE TITLE
Feature Request: Wait for Jenkins job status

### ISSUE THREAD

**Issue by tomer-ds** [appleboy/jenkins-action#4]
So I am wondering if this has ever come up already in the past...

I am of course using this to trigger my build jobs in Jenkins, but the action doesn't wait for the job to finish and the job's success or failure does not effect the end result of the action, which seems strange for me...

Maybe there is another action template that waits for success or failure of the Jenkins job that you can point me in the direction of? Or maybe it is something that can be added to this action...?

Or then again, maybe it is just some simple configuration that I missed...?

**Comment by SebastianScherer88** [comment]
bump. seems like a critical feature for any element in a CI/CD pipeline - being able to see if it has successful exit status, and make subsequent steps' execution conditional on said exit status

**Comment by appleboy** [comment]
See the PR: https://github.com/appleboy/drone-jenkins/pull/40

**Comment by appleboy** [comment]
```yml
- name: trigger Job and wait for completion
  uses: appleboy/jenkins-action@v1
  with:
    url: http://example.com
    user: example
    token: ${{ secrets.TOKEN }}
    job: job_1
    wait: true
    poll_interval: 5s
    timeout: 60m
```

Try it out.
