### ISSUE TITLE
i/o timeout error , when trying to call Jenkins job

### ISSUE THREAD

**Issue by IvanAksionau** [appleboy/jenkins-action#9]
Hi, Could anyone help me to understand the reason of getting error , described below?
![image](https://user-images.githubusercontent.com/22475527/180212256-81804612-a946-4950-b8fb-57fd8fd961a2.png)

# Here is my yaml file:
````
name: trigger pipeline on merged code changes
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, reopened ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://192.168.100.5:8080"
          user: "ivan"
          token: ${{ secrets.TOKEN }}
          job: "pipeline-selenium-tests"
````

# Jenkins is running based on DockerFile bellow:
````
FROM jenkins/jenkins:2.359

USER root
# install maven inside container
ARG MAVEN_VERSION=3.6.3
ARG USER_HOME_DIR="/root"
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
RUN mkdir -p /usr/share/maven /usr/share/maven/ref \
 && curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz \
 && tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 \
 && rm -f /tmp/apache-maven.tar.gz \
 && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

# install docker inside container
RUN mkdir -p /tmp/download && \
 curl -L https://download.docker.com/linux/static/stable/x86_64/docker-18.03.1-ce.tgz | tar -xz -C /tmp/download && \
 rm -rf /tmp/download/docker/dockerd && \
 mv /tmp/download/docker/docker* /usr/local/bin/ && \
 rm -rf /tmp/download && \
 groupadd -g 999 docker && \
 usermod -aG staff,docker jenkins

RUN curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose \
````
# I also generated a token for current Jenkins user and added required configuration for a job:

![image](https://user-images.githubusercontent.com/22475527/180216454-a56e72a4-3e66-4eef-b926-d392877801ac.png)

![image](https://user-images.githubusercontent.com/22475527/180216262-f34196f0-574a-4413-a5b1-81b38c5d6ff1.png)
